### ISSUE TITLE
unable to create user 

### ISSUE THREAD

**Issue by Jacobrosario** [treehouse-apprenticeship/athena_irv_team1#14]
Attempting to create a new user produces the following validation error on the server:

{
    "message": "Validation Failed",
    "errors": [
        "Cast to String failed for value \"Promise { <pending> }\" at path \"password\""
    ]
}

(for more information view the "issues.md" folder)

**Comment by minnja6** [comment]
Issue #14 resolved! @taufina @michelletyson @Jacobrosario
